spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: dfms-view
  jackson:
    serialization:
      write-date-keys-as-timestamps: true
external:
  amqp:
    queue: dfms.event.queue
axon:
  amqp:
    exchange: feeds.command.exchange.out
    durable-messages: true
    transaction-mode: transactional
  eventhandling:
    processors:
      dfmsItemProcessor:
        mode: subscribing
        source: springAMQPMessageSource
